version: "3.7"
services:
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
    restart: unless-stopped
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'

volumes:
  elasticsearch:

